obj-m := sockettest.o
sockettest-y := test/socket_test.o
sockettest-y += src/socket.o
ccflags-y := -I$(src)/include

#obj-m += tty_bridge_driver.o
#tty_bridge_driver-objs := tty_bridge_driver.o socket.o

